const faker = require('faker');
const state = require('./db/models/state');

const stateNames = faker.locales.en.address.state;
const stateAbbr = faker.locales.en.address.state_abbr;



{name: "Superstition Shadows Skatepark", city_id: 76, state_id: 3, country_id: 1, description: 'Apache Junction is a large flowing park with lots of transition & a snake run, but is a little mellower than other AZ parks for the middle school kids next door. Street elements surround the flow and make great lines.', image: "https://www.concretedisciples.com/media/reviews/photos/thumbnail/120x120c/fb/8e/0d/19254_apacheoverviewopt_1293994650.jpg", website: '', address: 'AZ-60 east, off at Ironwood, go north to Southern, turn east and the park will be on the right side, near the school'},
{name: "Bagdad Skatepark", city_id: 78, state_id: 3, country_id: 1, description: "1500 square feet, all concrete, with a super tight, 4' high, boob-shaped half-bowl to one side, and a 5' tall, medium-sized quarterpipe at the other end. In between, there's a short pyramid, a pair of 'nipple' shaped obstacles (I swear to God, I'm not making this up; GoogleMap it if you don't believe me!), a bench, and a curb-height box/manual pad.", image: "https://www.concretedisciples.com/media/reviews/photos/thumbnail/120x120c/38/36/18/bagdad-skatepark-bagdad-arizona-usa-16-1517812923.jpg", website: '', address: '700 Palo Verde Rd'},
{name: "City of Benson Skatepark", city_id: 79, state_id: 3, country_id: 1, description: "A prefab steel setup on a very smooth, concrete slab. The ramps are surprisingly well-built, fast, and fun, and the slab is also pretty smooth and fast (minus a few over-sized control joints). There are bathrooms directly across the street, and picnic benches, shade structures, and grills on site, if you're the sort of bloke that wants to chill and grill while you're skating. As far as obstacles go, all of the 'usual stuff' is present and accounts for: a large bank ramp; a mid-height quarterpipe; a bank-to-box-to-bank setup; a spined quarterpipe; and an array of railslide bars, benches, and boxes. The ramps look very 'Woodward Ramps' to me (not your typical Skatewave garbage), with the spine obviously being built by a different company. For such a small-town skatepark, this one is reasonably well done; it's worth the quick leg-stretcher stop if you happen to be cruising by on I-10. -Bud Stratford, Everything Skateboarding/Concrete Disciples. Tuesday, March 20th, 2018. They have a metal ramp setup now. Would be pretty cool except some dumba** decided to sandblast the graffiti off of the ramp. Ok; now they made it grip tape and you don't slide to your safety when you fall. Instead it grabs you, twists you & throws you down. But they have ramps now. - Joe Mudd, 3/2/2009", image: "https://www.concretedisciples.com/media/reviews/photos/thumbnail/120x120c/e3/e2/5b/city-of-benson-skate-park-benson-arizona-usa-11-1521598822.jpg", website: '', address: '298 W Pearl St'},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},
{name: "", city_id: 0, state_id: 3, country_id: 1, description: 'NA', image: "", website: '', address: ''},


{name: "", city_id: 0, state_id: 4, country_id: 1, description: 'NA', image: "", website: '', address: ''},
